
export const setLocalStorage = () => {
  const employees = [
    {
      id: 1,
      firstName: "Aarav",
      email: "e@e.com",
      password: "123",
      tasks: [
        {
          title: "Design Homepage",
          description: "Create a modern homepage UI",
          date: "2025-10-24",
          category: "Design",
          active: true,
          newTask: true,
          completed: false,
          failed: false,
        },
        {
          title: "Backend Setup",
          description: "Setup server and database",
          date: "2025-10-25",
          category: "Development",
          active: true,
          newTask: false,
          completed: true,
          failed: false,
        },
        {
          title: "API Integration",
          description: "Integrate payment API",
          date: "2025-10-26",
          category: "Development",
          active: false,
          newTask: false,
          completed: false,
          failed: true,
        },
      ],
      taskNumbers: { active: 2, newTask: 1, completed: 1, failed: 1 },
    },
    {
      id: 2,
      firstName: "Isha",
      email: "employee2@example.com",
      password: "123",
      tasks: [
        {
          title: "Create UI Kit",
          description: "Build reusable components for UI",
          date: "2025-10-24",
          category: "Design",
          active: true,
          newTask: true,
          completed: false,
          failed: false,
        },
        {
          title: "Database Optimization",
          description: "Optimize queries for speed",
          date: "2025-10-25",
          category: "Development",
          active: true,
          newTask: false,
          completed: true,
          failed: false,
        },
        {
          title: "Testing",
          description: "Write unit tests for app",
          date: "2025-10-26",
          category: "QA",
          active: true,
          newTask: false,
          completed: false,
          failed: false,
        },
        {
          title: "Client Meeting",
          description: "Discuss UI improvements",
          date: "2025-10-27",
          category: "Management",
          active: false,
          newTask: false,
          completed: true,
          failed: false,
        },
      ],
      taskNumbers: { active: 3, newTask: 1, completed: 2, failed: 0 },
    },
    {
      id: 3,
      firstName: "Rohan",
      email: "employee3@example.com",
      password: "123",
      tasks: [
        {
          title: "Write Blog Post",
          description: "Technical blog about React",
          date: "2025-10-24",
          category: "Content",
          active: true,
          newTask: true,
          completed: false,
          failed: false,
        },
        {
          title: "Update Docs",
          description: "Update API documentation",
          date: "2025-10-25",
          category: "Documentation",
          active: true,
          newTask: false,
          completed: true,
          failed: false,
        },
      ],
      taskNumbers: { active: 2, newTask: 1, completed: 1, failed: 0 },
    },
    {
      id: 4,
      firstName: "Priya",
      email: "employee4@example.com",
      password: "123",
      tasks: [
        {
          title: "Test Login Flow",
          description: "Test login and registration",
          date: "2025-10-24",
          category: "QA",
          active: true,
          newTask: true,
          completed: false,
          failed: false,
        },
        {
          title: "Design Dashboard",
          description: "Create dashboard UI",
          date: "2025-10-25",
          category: "Design",
          active: true,
          newTask: false,
          completed: true,
          failed: false,
        },
        {
          title: "Bug Fixing",
          description: "Fix reported bugs",
          date: "2025-10-26",
          category: "Development",
          active: false,
          newTask: false,
          completed: false,
          failed: true,
        },
        {
          title: "Code Review",
          description: "Review teammate PRs",
          date: "2025-10-27",
          category: "Development",
          active: false,
          newTask: false,
          completed: true,
          failed: false,
        },
        {
          title: "Deploy App",
          description: "Deploy the application to staging",
          date: "2025-10-28",
          category: "Deployment",
          active: false,
          newTask: false,
          completed: true,
          failed: false,
        },
      ],
      taskNumbers: { active: 2, newTask: 1, completed: 3, failed: 1 },
    },
    {
      id: 5,
      firstName: "Neha",
      email: "employee5@example.com",
      password: "123",
      tasks: [
        {
          title: "Setup Analytics",
          description: "Integrate Google Analytics",
          date: "2025-10-24",
          category: "Marketing",
          active: true,
          newTask: true,
          completed: false,
          failed: false,
        },
        {
          title: "Create Landing Page",
          description: "Build landing page for product",
          date: "2025-10-25",
          category: "Design",
          active: true,
          newTask: false,
          completed: true,
          failed: false,
        },
        {
          title: "Email Campaign",
          description: "Prepare email marketing campaign",
          date: "2025-10-26",
          category: "Marketing",
          active: true,
          newTask: false,
          completed: false,
          failed: false,
        },
      ],
      taskNumbers: { active: 3, newTask: 1, completed: 1, failed: 0 },
    },
  ];

  const admin = [{ id: 1, email: "admin@me.com", password: "123" }];

  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees")) || [];
  const admin = JSON.parse(localStorage.getItem("admin")) || [];
  return { employees, admin };
};
